sudo: required
env:
  matrix:
  - OS_TYPE=centos OS_VERSION=6
  - OS_TYPE=centos OS_VERSION=7
  
services:
  - docker
  
before_install:
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - sudo docker pull centos:centos${OS_VERSION}

  
script:
 # Run tests in Container
 - docker run --privileged -d -ti -e "container=docker"  -v /sys/fs/cgroup:/sys/fs/cgroup -v `pwd`:/htcondor-ce:rw  centos:centos${OS_VERSION}   /usr/sbin/init
 - DOCKER_CONTAINER_ID=$(docker ps | grep centos | awk '{print $1}')
 - docker logs $DOCKER_CONTAINER_ID
 - >
   docker exec -ti $DOCKER_CONTAINER_ID /bin/bash -c "bash -xe /htcondor-ce/tests/test_inside_docker.sh ${OS_VERSION}
     echo -ne \"------\nEND HTCONDOR-CE TESTS\n------\nSystemD Units:\n------\n\";
     systemctl --no-pager --all --full status
     echo -ne \"------\nJournalD Logs:\n------\n\" ;
     journalctl --catalog --all --full --no-pager"
 - docker ps -a
 - docker stop $DOCKER_CONTAINER_ID
 - docker rm -v $DOCKER_CONTAINER_ID


