site_name: HTCondor-CE Documentation
site_url: https://htcondor.github.io/htcondor-ce-ce
repo_url: https://github.com/htcondor/htcondor-ce/

theme:
  name: material
  features:
    - navigation.tabs

extra_css:
  - css/superfences.css
  - css/extra.css

nav:
- Home: 'index.md'
- HTCondor-CE 5:
  - Installation: 'v5/installation/htcondor-ce.md'
  - Batch System Integration: 'v5/batch-system-integration.md'
  - Verification: 'v5/verification.md'
  - Troubleshooting: 'v5/troubleshooting/troubleshooting.md'
  - Central Grid Operations:
    - Submit Jobs Remotely: 'v5/remote-job-submission.md'
    - Remote Troubleshooting: 'v5/troubleshooting/remote-troubleshooting.md'
    - Install a Central Collector: 'v5/installation/central-collector.md'
  - Releases: 'v5/releases.md'
  - Reference: 'v5/reference.md'
- HTCondor-CE 4:
  - Installation: 'v4/installation/htcondor-ce.md'
  - Batch System Integration: 'v4/batch-system-integration.md'
  - Verification: 'v4/verification.md'
  - Troubleshooting: 'v4/troubleshooting/troubleshooting.md'
  - Central Grid Operations:
    - Submit Jobs Remotely: 'v4/remote-job-submission.md'
    - Remote Troubleshooting: 'v4/troubleshooting/remote-troubleshooting.md'
    - Install a Central Collector: 'v4/installation/central-collector.md'
  - Releases: 'v4/releases.md'
  - Reference: 'v4/reference.md'
- HTCondor-CE 3:
  - Installation: 'v3/installation/htcondor-ce.md'
  - Batch System Integration: 'v3/batch-system-integration.md'
  - Verification: 'v3/verification.md'
  - Troubleshooting: 'v3/troubleshooting/troubleshooting.md'
  - Releases: 'v3/releases.md'
  - Reference: 'v3/reference.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - toc:
      permalink: True
  - pymdownx.superfences
