site_name: HTCondor-CE Documentation
site_url: https://htcondor-ce.org
repo_url: https://github.com/htcondor/htcondor-ce/

theme:
  name: material
  features:
    - navigation.tabs

extra_css:
  - css/superfences.css
  - css/extra.css

nav:
- HTCondor-CE 4 and 5:
  - Home: 'index.md'
  - Overview: 'overview.md'
  - Installation: 'installation/htcondor-ce.md'
  - Batch System Integration: 'batch-system-integration.md'
  - Verification: 'verification.md'
  - Troubleshooting: 'troubleshooting/troubleshooting.md'
  - Releases: 'releases.md'
  - Central Grid Operations:
    - Submit Jobs Remotely: 'remote-job-submission.md'
    - Remote Troubleshooting: 'troubleshooting/remote-troubleshooting.md'
    - Install a Central Collector: 'installation/central-collector.md'
  - Reference: 'reference.md'
- HTCondor-CE 3:
  - Home: 'v3/index.md'
  - Overview: 'v3/overview.md'
  - Installation: 'v3/installation/htcondor-ce.md'
  - Batch System Integration: 'v3/batch-system-integration.md'
  - Verification: 'v3/verification.md'
  - Troubleshooting: 'v3/troubleshooting/troubleshooting.md'
  - Releases: 'v3/releases.md'
  - Reference: 'v3/reference.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - toc:
      permalink: True
  - pymdownx.superfences
