name: Build HTCondor-CE RPMs
on: [pull_request, push]

jobs:
  build-rpms-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dver: [7, 8]
        target_env: [osg, uw_build]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare Docker
        run: |
          echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null &&
            sudo service docker restart

      - name: Start CentOS ${{ matrix.dver}} image
        run: |
          docker run --privileged --detach --env "container=docker" \
                 --name ${{ matrix.target_env }}-${{ matrix.dver }} \
                 --volume /sys/fs/cgroup:/sys/fs/cgroup \
                 --volume `pwd`:/htcondor-ce:rw \
                 centos:centos${{ matrix.dver }} \
                 /usr/sbin/init

      - run: tests/setup_tests.sh ${{ matrix.dver }} ${{ matrix.target_env }}

